#! /usr/bin/env bash

prefix=/usr/local/bin
BINS=$( basename bin/*)

if [[ -e orgname ]]; then
	ORG=$( cat orgname)
fi

if [[ -z ORG ]]; then
	ORG=dcgov
fi

function clean() {
	echo "Removing ${ORG} command"
	rm ${prefix}/${ORG}
	for cmd in ${BINS}; do
		echo "Removing ${cmd} subcommand"
		rm ${prefix}/${ORG}-${cmd}
	done
}

clean
