#! /usr/bin/env bash

prefix=/usr/local/bin
BINS=$( basename bin/*)

if [[ -e orgname ]]; then
	ORG=$( cat orgname)
fi

if [[ -z ORG ]]; then
	ORG=dcgov
fi

function setup() {
	echo "Installing ${ORG} command"
	mkdir -p ${prefix}
	install -d -m 0755 ${prefix}
	install -m 0755 orgwide ${prefix}
	mv ${prefix}/orgwide ${prefix}/${ORG}
	for cmd in ${BINS}; do
		echo "Installing ${cmd} subcommand"
		mv bin/${cmd} bin/${ORG}-${cmd}
		install -m 0755 bin/${ORG}-${cmd} ${prefix}
		mv bin/${ORG}-${cmd} bin/${cmd}
	done
}

setup

